feat_root: '/root/autodl-tmp/0-pipei-dinov3/feats_512/dinov3_vith16plus'
output_dir: '/root/autodl-tmp/0-pipei-dinov3/outputs/unsupervised_srdae_512'
#save_name: 'srdae_model_23_26_291536.pth'
save_name: 'srdae_model_26_28v.pth'

# fusion_layers: [28, 31] #v12
# input_dim: 2560
# latent_dim: 1280

# fusion_layers: [22, 26, 31] #v12
# input_dim: 3840
# latent_dim: 1280

# fusion_layers: [20, 23, 26, 30] #v12
# input_dim: 5120
# latent_dim: 1280

fusion_layers: [26, 28] #v12
input_dim: 2580
latent_dim: 1280

# fusion_layers: [27, 28] #v12
# input_dim: 2580
# latent_dim: 1280

# fusion_layers: [23, 26, 29] #v12
# input_dim: 3840
# latent_dim: 1280
#latent_dim: 1080
#latent_dim: 1536

# fusion_layers: [22, 26, 29] #v12
# input_dim: 3840
# latent_dim: 1280

# fusion_layers: [23, 26, 30] #v12
# input_dim: 3840
# latent_dim: 1280

# fusion_layers: [22, 26, 30] #v12
# input_dim: 3840
# latent_dim: 1280

# fusion_layers: [21, 22, 23, 24, 25, 26, 27, 29, 30, 31] #v13 2560    v14 1280
# input_dim: 12800
# latent_dim: 2560

train:
  batch_size: 256
  epochs: 40
  lr: 0.001
  warmup_epochs: 5
  drop_rate: 0.0       # 0.1 -> 0.0 (Removal)
  
  # Loss Balancing
  lambda_recon: 0.5
  #lambda_decov: 100.0   # 保持高去相关
  lambda_decov: 100.0   # 保持高去相关
  #lambda_orth: 5.0     # 约束
  lambda_orth: 10.0     # 约束
  #lambda_sparse: 0.05  # 0.001 -> 0.02 (20倍! 逼迫 Gamma 变小)
  lambda_sparse: 0.001  # 0.001 -> 0.02 (20倍! 逼迫 Gamma 变小)
  #lambda_sparse: 0.2  # 效果不好
  #lambda_sparse: 0.02  # 效果不好